from typing import Literal, Optional, TypedDict

from langgraph.checkpoint.memory import MemorySaver
from langgraph.graph import END, START, StateGraph
from langgraph.types import Command, interrupt


# ==========================================
# 1. State Schema
# ==========================================
class AgentState(TypedDict):
    scenario: str
    action_type: str
    approved: Optional[bool]
    result: Optional[str]
    
    # Tracking executions to prove the node restarts
    node_entry_count: int

# ==========================================
# 2. Preparation Node
# ==========================================
def prepare_node(state: AgentState):
    print(f"\n{'='*60}\n[Scenario]: {state['scenario']}")
    print(f"  [Prepare] Staging action: '{state['action_type']}'")
    return {"node_entry_count": 0}

# ==========================================
# 3. The Approval Node (The Tricky Part)
# ==========================================
def approval_node(state: AgentState):
    """
    WARNING: When resumed, LangGraph re-enters this node from the TOP.
    Do not put side-effects before the interrupt() call here!
    """
    entry_count = state.get("node_entry_count", 0) + 1
    print(f"  [Approval Node] Entered node. (Entry count: {entry_count})")
    
    # THE PAUSE BOUNDARY
    # On first run, execution stops here. 
    # On resume run, this instantly returns the resumed value instead of pausing.
    approved = interrupt({
        "question": f"Do you approve the execution of '{state['action_type']}'?",
        "action": state["action_type"]
    })
    
    print(f"  [Approval Node] Received resume value: {approved}")
    return {"approved": approved, "node_entry_count": entry_count}

# ==========================================
# 4. Router & Execution
# ==========================================
def route_approval(state: AgentState) -> Literal["execute_action", "__end__"]:
    # We explicitly check for True, rejecting None or False
    if state.get("approved") is True:
        print("  [Router] Approved. Proceeding to execution.")
        return "execute_action"
    
    print("  [Router] Rejected. Aborting.")
    return "__end__"

def execute_action_node(state: AgentState):
    print(f"  [Execution] Running side-effect for: {state['action_type']}...")
    return {"result": "success"}

# ==========================================
# 5. Build Graph
# ==========================================
builder = StateGraph(AgentState)

builder.add_node("prepare", prepare_node)
builder.add_node("approval", approval_node)
builder.add_node("execute_action", execute_action_node)

builder.add_edge(START, "prepare")
builder.add_edge("prepare", "approval")
builder.add_conditional_edges("approval", route_approval)
builder.add_edge("execute_action", END)

memory = MemorySaver()
graph = builder.compile(checkpointer=memory)

# ==========================================
# 6. Execution Simulation
# ==========================================
def simulate_pause_resume(thread_id: str, scenario: str, human_response: bool):
    config = {"configurable": {"thread_id": thread_id}}
    
    # --- 1. FIRST INVOCATION (PAUSES) ---
    print(f"  [API] Starting graph invocation for thread '{thread_id}'...")
    initial_state = {"scenario": scenario, "action_type": "deploy_to_production", "approved": None, "result": None, "node_entry_count": 0}
    
    # Use invoke. It will return the state at the point of interruption.
    paused_state = graph.invoke(initial_state, config)
    
    # We can inspect the interrupt data generated by the graph
    interrupts = paused_state.get("__interrupts__", tuple())
    if interrupts:
        print(f"  [API] Graph paused! Interrupt payload: {interrupts[0].value}")
    else:
        print("  [API] Graph finished without pausing.")
        return
        
    print("  [API] Returning 200 OK to frontend. Process exiting...")
    print("  ... time passes ...")
    
    # --- 2. SECOND INVOCATION (RESUMES) ---
    print(f"  [API] Received POST /resume with value '{human_response}'. Resuming thread '{thread_id}'...")
    
    # Invoke again using a Command to inject the response directly into the interrupted node
    final_state = graph.invoke(Command(resume=human_response), config)
    
    if final_state.get("result"):
        print(f"  [API] Graph finished successfully.")
    else:
        print(f"  [API] Graph aborted.")

# Run Scenarios
simulate_pause_resume("thread-101", "Approve Path", True)
simulate_pause_resume("thread-102", "Reject Path", False)