from typing import TypedDict, Literal, Optional, List
from langgraph.graph import StateGraph, START, END
from langgraph.checkpoint.memory import MemorySaver
from langgraph.types import interrupt, Command

# ==========================================
# 1. State Schema
# ==========================================
class AgentState(TypedDict):
    scenario: str
    action_payload: dict
    
    # Track the independent approvals
    manager_decision: Optional[str]
    finance_decision: Optional[str]
    
    final_status: Literal["pending", "approved", "rejected", "executed"]

# ==========================================
# 2. Nodes
# ==========================================
def prepare_node(state: AgentState):
    print(f"\n{'='*60}\n[Scenario]: {state['scenario']}")
    print(f"  [Prepare] Agent proposes high-value action: {state['action_payload']}")
    return {"final_status": "pending"}

def manager_approval_node(state: AgentState):
    """Parallel Node 1"""
    # If it was already approved in a previous resume, skip the interrupt
    if state.get("manager_decision"):
        return {}
        
    print("  [Manager Node] Interrupting for Manager Approval...")
    decision = interrupt({"role": "manager", "action": state["action_payload"]})
    print(f"  [Manager Node] Resumed with decision: {decision}")
    return {"manager_decision": decision}

def finance_approval_node(state: AgentState):
    """Parallel Node 2"""
    # If it was already approved in a previous resume, skip the interrupt
    if state.get("finance_decision"):
        return {}
        
    print("  [Finance Node] Interrupting for Finance Approval...")
    decision = interrupt({"role": "finance", "action": state["action_payload"]})
    print(f"  [Finance Node] Resumed with decision: {decision}")
    return {"finance_decision": decision}

def aggregate_node(state: AgentState):
    """The ALL Policy Engine"""
    mgr = state.get("manager_decision")
    fin = state.get("finance_decision")
    
    print(f"  [Aggregator] Current State -> Manager: {mgr} | Finance: {fin}")
    
    # 1. ANY Rejection instantly kills the workflow
    if mgr == "reject" or fin == "reject":
        print("    -> A required approver rejected the action. Aborting.")
        return {"final_status": "rejected"}
        
    # 2. ALL must approve to proceed
    if mgr == "approve" and fin == "approve":
        print("    -> ALL required approvals secured. Proceeding to execution.")
        return {"final_status": "approved"}
        
    # 3. Still waiting on someone
    print("    -> Waiting for remaining approvals...")
    return {}

def execute_node(state: AgentState):
    print("  [Execution] Side effect executed successfully!")
    return {"final_status": "executed"}

# ==========================================
# 3. Router
# ==========================================
def route_aggregation(state: AgentState) -> Literal["execute", "__end__"]:
    if state["final_status"] == "approved":
        return "execute"
    if state["final_status"] == "rejected":
        return "__end__"
    
    # If still pending, end this specific execution loop. The graph remains paused 
    # at the remaining interrupt(s) until resumed again.
    return "__end__"

# ==========================================
# 4. Build Graph
# ==========================================
builder = StateGraph(AgentState)

builder.add_node("prepare", prepare_node)
builder.add_node("manager_approval", manager_approval_node)
builder.add_node("finance_approval", finance_approval_node)
builder.add_node("aggregate", aggregate_node)
builder.add_node("execute", execute_node)

builder.add_edge(START, "prepare")

# Fan out in parallel!
builder.add_edge("prepare", "manager_approval")
builder.add_edge("prepare", "finance_approval")

# Fan in
builder.add_edge("manager_approval", "aggregate")
builder.add_edge("finance_approval", "aggregate")

builder.add_conditional_edges("aggregate", route_aggregation)
builder.add_edge("execute", END)

memory = MemorySaver()
graph = builder.compile(checkpointer=memory)

# ==========================================
# 5. Backend API Simulation
# ==========================================
def api_resolve_approvals(thread_id: str, scenario: str, manager_resp: str = None, finance_resp: str = None):
    config = {"configurable": {"thread_id": thread_id}}
    
    # START
    initial_state = {"scenario": scenario, "action_payload": {"type": "refund", "amount": 10000}, "manager_decision": None, "finance_decision": None, "final_status": "pending"}
    for _ in graph.stream(initial_state, config): pass
    
    paused_state = graph.get_state(config)
    
    # We must map responses to the specific interrupt IDs generated by LangGraph
    interrupts = paused_state.tasks[0].interrupts if paused_state.tasks else []
    resume_payload = {}
    
    for intr in interrupts:
        if intr.value["role"] == "manager" and manager_resp:
            resume_payload[intr.id] = manager_resp
        elif intr.value["role"] == "finance" and finance_resp:
            resume_payload[intr.id] = finance_resp
            
    if resume_payload:
        print("\n  [API] Submitting responses to LangGraph...")
        graph.invoke(Command(resume=resume_payload), config)

# Scenarios
# 1. Both approve immediately
api_resolve_approvals("thread-1", "Both Approve", manager_resp="approve", finance_resp="approve")

# 2. Manager approves, but Finance rejects (Kills the workflow)
api_resolve_approvals("thread-2", "Finance Rejects", manager_resp="approve", finance_resp="reject")

# 3. Manager approves, Finance hasn't responded yet (Workflow remains pending)
api_resolve_approvals("thread-3", "Waiting on Finance", manager_resp="approve", finance_resp=None)