import operator
from typing import Annotated, Literal

from langgraph.graph import END, START, StateGraph
from typing_extensions import TypedDict


# ==========================================
# 1. State Schema
# ==========================================
class State(TypedDict):
    user_task: str
    plan: list[str]            # The sequence of steps generated by the planner
    current_step: int          # Tracks where we are in the plan
    # Reducer added so executor can append results one by one
    results: Annotated[list[str], operator.add] 

# ==========================================
# 2. Nodes
# ==========================================
def planner(state: State):
    task = state["user_task"].lower()
    print(f"\n[Planner] Analyzing task: '{state['user_task']}'")
    
    # Deterministic planning logic (No LLM yet!)
    if "research" in task:
        plan = [
            "Collect information",
            "Analyze information",
            "Write summary"
        ]
    else:
        plan = [
            "Process request"
        ]
        
    print(f"[Planner] Generated {len(plan)}-step plan.")
    
    # We reset current_step to 0 in case this is a replan later
    return {"plan": plan, "current_step": 0}

def executor(state: State):
    # Fetch the exact step we need to execute based on the index
    step_index = state["current_step"]
    step_name = state["plan"][step_index]
    
    print(f"  [Executor] Step {step_index + 1}: {step_name}")
    
    # Simulate the work
    simulated_result = f"Executed: {step_name}"
    
    # Increment step counter, and return the result as a LIST so the reducer appends it
    return {
        "current_step": step_index + 1,
        "results": [simulated_result]
    }

# ==========================================
# 3. Router
# ==========================================
def route_execution(state: State) -> Literal["executor", END]:
    # Have we reached the end of the plan?
    if state["current_step"] < len(state["plan"]):
        return "executor"
    
    print("  [Router] Plan complete. Routing to END.")
    return END

# ==========================================
# 4. Build & Compile
# ==========================================
builder = StateGraph(State)

builder.add_node("planner", planner)
builder.add_node("executor", executor)

builder.add_edge(START, "planner")
builder.add_edge("planner", "executor")

builder.add_conditional_edges(
    "executor", 
    route_execution,
    {"executor": "executor", END: END}
)

graph = builder.compile()

# ==========================================
# 5. Execution Tests
# ==========================================

print("=== TEST 1: Complex Task (Requires Planning) ===")
result_1 = graph.invoke({
    "user_task": "Research LangGraph",
    "plan": [],
    "current_step": 0,
    "results": []
})
print("\nFinal State for Test 1:")
for k, v in result_1.items():
    print(f"  {k}: {v}")


print("\n\n=== TEST 2: Simple Task ===")
result_2 = graph.invoke({
    "user_task": "Say hello",
    "plan": [],
    "current_step": 0,
    "results": []
})
print("\nFinal State for Test 2:")
for k, v in result_2.items():
    print(f"  {k}: {v}")